### ISSUE TITLE
Library name differs from the original version

### ISSUE THREAD

**Issue by ax487** [ambasta/or-tools#1]
I noticed a small problem with the naming of the project / library:

The project name is set to `PROJECT(or_tools LANGUAGES CXX)`, i.e. it has the value `or_tools`.

Later, a library is built using the project name as library name: 

    ADD_LIBRARY(${PROJECT_NAME} SHARED ${SUBTARGETS})

So the library is named `libor_tools.so` rather than the original `libortools.so`. I think that you should rename the library to the latter (maybe by renaming the project as well?). I think that the google devs will not merge your repo if that means that everyone using the library will have to change their compiler flags. I think this is probably a one-liner to fix though.

**Comment by ambasta** [comment]
Thanks for pointing this out. Resolved in commit 72e33137849df7c27ef5a3b26d24f3f09221cbb8
