### ISSUE TITLE
Compilation of the examples fails

### ISSUE THREAD

**Issue by ax487** [ambasta/or-tools#2]
I tried compiling the code in your repo. I managed to compile the library without problems using

    mkdir build && cd build
    cmake .. -DBUILD_CXX=true
    make

That is, I am using an out-of-tree build. Unfortunately the build of the examples later on fails with the following error message:

    examples/cpp/jobshop_earlytardy.cc:87:47: error: ‘CBC_MIXED_INTEGER_PROGRAMMING’ is not a member of ‘operations_research::MPSolver’
         mp_solver_("TimePlacement", MPSolver::CBC_MIXED_INTEGER_PROGRAMMING) {}

It is also the case that I don't have `cbc` available as a solver, so the corresponding define is not included:

        #ifdef USE_CBC
        CBC_MIXED_INTEGER_PROGRAMMING = 5,
        #endif

To be fair, I don't know if this is not perhaps an upstream problem. Maybe you should disable this example if cbc is not installed. Otherwise the example should be modified somehow.

Edit: In the upstream version the Cbc library is statically compiled into the binary, so it is available in any case.

**Comment by ambasta** [comment]
Hi @ax487 

The build has been updated to build CBC internally if its not available system wide. This should be resolved for now. However, I am trying to understand the possible configurations that ortools supports and allow for alternatives when CBC isn't available but one of the other libraries are!

**Comment by ambasta** [comment]
Hi @ax487 
I am assuming this issue has been resolved since the fork too now statically compiles against cbc if missing. I'm closing this issue for now, but feel free to re-open it if the issue persists!
