### ISSUE TITLE
OS X link error. 

### ISSUE THREAD

**Issue by mjfwest** [ambasta/or-tools#5]
New issue directed at the fork. [Issue   ##406](https://github.com/google/or-tools/issues/406)
Hello @ambasta,
It seems that change works. It now gets further to:
```
Scanning dependencies of target ortools
[ 77%] Linking CXX shared library libortools.dylib
```
then follows thousands of lines of
```
duplicate symbol __SomeSymbol in:
    ortools/constraint_solver/CMakeFiles/ortools_constraint_solver.dir/SomeFile.pb.cc.o
    CMakeFiles/ortoolsProto.dir/ortools/constraint_solver/SomeFile.pb.cc.o
```
followed by:
```
ld: 2692 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libortools.dylib] Error 1
make[1]: *** [CMakeFiles/ortools.dir/all] Error 2
make: *** [all] Error 2
```
so it seems something is getting included twice?

Full Build log
https://gist.github.com/mjfwest/d747125e7106684fba5db9312e4f0ed4

**Comment by ambasta** [comment]
Did you build in the source directory or a subdirectory?

i.e. git clone <repo> <srcdir> && mkdir build && cd build && rm -fR * && cmake .. && make

I can see that bop_parameters.pb.cc.o has been compiled exactly once
Line 213: Building CXX object ortools/bop/CMakeFiles/ortools_bop.dir/bop_parameters.pb.cc.o

But has been included/linked twice

ortools/bop/CMakeFiles/ortools_bop.dir/bop_parameters.pb.cc.o CMakeFiles/ortoolsProto.dir/ortools/bop/bop_parameters.pb.cc.o

I am not sure where the second entry is coming from unless from a previous build

**Comment by mjfwest** [comment]
Thanks, you diagnosed it correctly.  
I did a `git clean -xdf` then `git reset --hard` followed by `mkdir build && cd build && rm -fR * && cmake .. && make` and it compiled all the way.
